export const ErrorCodes = {
    COMMAND_LOAD_ERROR: "CMD-0001",

    COMMAND_EXPORT_MISSING: "CMD-0002",

    COMMAND_DATA_MISSING: "CMD-0003",

    COMMAND_EXECUTE_MISSING: "CMD-0004",

    EVENT_NAME_MISSING: "EVT-0001",

    EVENT_EXECUTE_MISSING: "EVT-0002",

    CONFIG_INVALID: "CFG-0001",

    CONTAINER_ERROR: "CNT-0001",

    DISCORD_CONNECTION_ERROR: "DSC-0001",

    PROXY_ERROR: "PRX-0001",
} as const;
